/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ControladorNormativa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author USUARIO
 */
public class ConsultarNormativa extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarNormativa
     */
    public ConsultarNormativa() throws SQLException {
        initComponents();       
        ArrayList<Normativa> listaNormativa = new ArrayList<Normativa>();
        ControladorNormativa controladorNormativa = new ControladorNormativa();
        this.setSize(1200, 500);
        this.jTreeNormatividad.setSize(900, 490);

        listaNormativa = controladorNormativa.consultarNormativa("NORMA", "", "");

        for (int i = 0; i < listaNormativa.size(); i++) {
            jComboBoxNormas.addItem(listaNormativa.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxNormas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeNormatividad = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jComboBoxNormas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxNormasMouseClicked(evt);
            }
        });

        jTreeNormatividad.setPreferredSize(new java.awt.Dimension(800, 490));
        jScrollPane1.setViewportView(jTreeNormatividad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxNormas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jComboBoxNormas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNormasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxNormasMouseClicked
        ControladorNormativa controladorNormativa = new ControladorNormativa();
        ArrayList<Normativa> listaNormativa = new ArrayList<Normativa>();
        ArrayList<Normativa> listaDominios = new ArrayList<Normativa>();
        ArrayList<Normativa> listaCategorias = new ArrayList<Normativa>();
        ArrayList<Normativa> listaControles = new ArrayList<Normativa>();
        Normativa normativa = new Normativa();
        normativa = (Normativa) jComboBoxNormas.getSelectedItem();

        try {
            //listaNormativa = controladorNormativa.consultarNormativa("NORMATIVA",normativa.nombre,"");
            listaDominios = controladorNormativa.consultarNormativa("DOMINIO", normativa.codigo, "");
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarNormativa.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultMutableTreeNode dominios = new DefaultMutableTreeNode("Dominios");
        for (int i = 0; i < listaDominios.size(); i++) {
            DefaultMutableTreeNode dominio = new DefaultMutableTreeNode(listaDominios.get(i).nombre);
            dominios.add(dominio);
            try {
                listaCategorias = controladorNormativa.consultarNormativa("CATEGORIA", normativa.codigo, listaDominios.get(i).codigo);

                for (int j = 0; j < listaCategorias.size(); j++) {
                    DefaultMutableTreeNode categoria = new DefaultMutableTreeNode(listaCategorias.get(j).nombre);
                    dominio.add(categoria);
                    listaControles = controladorNormativa.consultarNormativa("CONTROL", normativa.codigo, listaCategorias.get(j).codigo);

                    for (int k = 0; k < listaControles.size(); k++) {
                        DefaultMutableTreeNode control = new DefaultMutableTreeNode(listaControles.get(k).nombre);
                        categoria.add(control);
                        DefaultMutableTreeNode descripcionControl = new DefaultMutableTreeNode(listaControles.get(k).descripcion);
                        control.add(descripcionControl);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ConsultarNormativa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        DefaultTreeModel dtm = new DefaultTreeModel(dominios);
        jTreeNormatividad.setModel(dtm);
    }//GEN-LAST:event_jComboBoxNormasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarNormativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarNormativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarNormativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarNormativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConsultarNormativa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ConsultarNormativa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxNormas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeNormatividad;
    // End of variables declaration//GEN-END:variables
}
